### ISSUE TITLE
KEYS redis command not working?

### ISSUE THREAD

**Issue by sandyplace** [microsoft/garnet#246] opened 2024-04-05 23:19 UTC
using the docker image and running GarnetServer in non-cluster mode when using redis-cli 
the KEYS command just returns a not connected status and hangs
<img width="240" alt="image" src="https://github.com/microsoft/garnet/assets/3067065/5a842305-83b7-44ca-81de-b1ca43db2fbb">

Is the KEYS command supported yet?

It also seems to hang when using the nodejs ioredis package when making a call to get the keys.

**Comment by MojtabaTajik** [comment] 2024-04-08 12:03
Do you have any extra info to reproduce the issue? I can't reproduce it.

![image](https://github.com/microsoft/garnet/assets/15414923/3f480337-88ae-464b-b146-cbbb691ba72d)

**Comment by sandyplace** [comment] 2024-04-08 15:45
I figured it out, I was trying to reduce the memory footprint as I noticed it was taking up 10gb in my local machine dev environment using docker/k8s. I was passing the following configuration to try create a smaller footprint for local testing:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: registry.gitlab.com/worksight/container-registry/ws-redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: client
          command: [
              "/app/GarnetServer",
              "--index",
              "1073742849",
              "--checkpointdir",
              "/data",
              "--aof",
              "--port",
              "6379",
            ]
          resources:
            requests:
              memory: "3Gi"
              cpu: "1000m"
            limits:
              memory: "3Gi"
              cpu: "4000m"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: redis-data
              mountPath: /data
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: LoadBalancer
  ports:
    - name: redis-port
      port: 6379
      protocol: TCP # default; can also specify UDP
  selector:
    app: redis
```

**Comment by vazois** [comment] 2024-04-09 18:21
Are you still facing the issue above or is it resolved?

**Comment by vazois** [comment] 2024-04-10 20:36
It looks like the issue was result of configuration issue. Closing the issue until otherwise.

**Closed by vazois** 2024-04-10 20:36 UTC
Labels: bug

**Comment by cduluCNB** [comment] 2024-04-11 15:50
This seems to be the same issue as #143, this memory usage is by design and configurable.
