### ISSUE TITLE
[BUG]: SPOP command return `Error: server closed the connection`

### ISSUE THREAD

**Issue by Zzhiter** [microsoft/garnet#190] opened 2024-03-29 06:44 UTC
![image](https://github.com/microsoft/garnet/assets/61727602/9f355a7c-1f2a-4b01-8950-a35ac3831908)
Looks like a bug, this happens when all elements in the collection are popped out。

**Comment by tisilent** [comment] 2024-03-29 07:26
#186  same

**Comment by TalZaccai** [comment] 2024-03-29 17:45
Duplicate of #186

**Closed by TalZaccai** 2024-03-29 17:45 UTC
Labels: bug
