### ISSUE TITLE
Is Garnet Support Multi DB?

### ISSUE THREAD

**Issue by zhoucheng3** [microsoft/garnet#877] opened 2024-12-13 03:51 UTC
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Is Garnet Support Multi DB?

### Describe the solution you'd like

Is Garnet Support Multi DB?

**Comment by Vijay-Nirmal** [comment] 2024-12-13 10:30
Duplicate of #61

> The default, and only, database in Garnet at the moment is 0 (zero).

**Closed** 2024-12-13 19:55 UTC
