### ISSUE TITLE
Add a unified prefix-key   by auth user/application in service side to enable multiple applications to share the same garnet service

### ISSUE THREAD

**Issue by springmin** [microsoft/garnet#470] opened 2024-06-18 03:37 UTC
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Garrnet  is so high performence ,multiple applications sharing a garnet server is good idea to shudown cost,   

### Describe the solution you'd like

Extend configuration options and implement default prefixes and configure default prefixes  for each authenticated user according to rules based on authenticated users

**Comment by TalZaccai** [comment] 2024-06-20 18:08
Duplicate of #415

**Closed by TalZaccai** 2024-06-20 18:08 UTC

**Comment by esafak** [comment] 2024-07-30 18:49
@TalZaccai Was this completed as implemented? If so, what was the PR?
